version: "3"
services:
  frontend:
    container_name: front
    build:
      context: ./frontend
      dockerfile: Dockerfile
    image: client
    environment:
      - REACT_APP_API_URL=${REACT_APP_API_URL}
    ports:
      - '3000:3000'
    volumes:
      - ./frontend/src:/app/src
    networks:
      - postgres

  database:
    image: postgres:14-alpine
    restart: always
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
    container_name: postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - postgres

  backend:
    container_name: back
    build:
      context: ./backend
      dockerfile: Dockerfile
    image: server
    environment:
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_HOST=${DB_HOST}
      - POSTGRES_PORT=${DB_PORT}
      - POSTGRES_SYNC=false
      - NODE_ENV=${NODE_ENV}
      - NODE_SERVER_PORT=${NODE_SERVER_PORT}
      - JWT_SECRET_KEY=${JWT_SECRET_KEY}
      - EMAIL_AUTH_EMAIL=${EMAIL_AUTH_EMAIL}
      - EMAIL_AUTH_PASSWORD=${EMAIL_AUTH_PASSWORD}
      - EMAIL_HOST=${EMAIL_HOST}
      - EMAIL_FROM_USER_NAME=${EMAIL_FROM_USER_NAME}
      - TOKEN_URI=${TOKEN_URI}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - CB_URI=${CB_URI}
    networks:
      - postgres
    ports:
      - '5000:5000'
    volumes:
      - ./backend/src:/app/src
    depends_on:
      - database

volumes:
  postgres:

networks:
  postgres:
